# Generated by Django 3.2.18 on 2023-03-08 15:14

from django.db import migrations, models
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, upload_to='members/')),
                ('user', models.ForeignKey(on_delete=models.CASCADE, to='auth.User')),

            ],
        ),
    ]
